// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1.gokit_with_grpc.proto

package v1_gokit_with_grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_eff6f5ecab6c4596, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreateUserRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eff6f5ecab6c4596, []int{1}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Response struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_eff6f5ecab6c4596, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "v1.gokit_with_grpc.grpc.User")
	proto.RegisterType((*CreateUserRequest)(nil), "v1.gokit_with_grpc.grpc.CreateUserRequest")
	proto.RegisterType((*Response)(nil), "v1.gokit_with_grpc.grpc.Response")
}

func init() { proto.RegisterFile("v1.gokit_with_grpc.proto", fileDescriptor_eff6f5ecab6c4596) }

var fileDescriptor_eff6f5ecab6c4596 = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x4d, 0x4b, 0x80, 0x40,
	0x10, 0x86, 0xd1, 0xbe, 0x6c, 0x0e, 0x41, 0x83, 0xd4, 0xe2, 0xa9, 0xa4, 0x43, 0x74, 0x58, 0xb0,
	0xfe, 0x41, 0x1d, 0xbc, 0x1b, 0x12, 0xd4, 0x41, 0x36, 0x1d, 0x74, 0x29, 0xdb, 0x6d, 0x67, 0xd3,
	0xbf, 0x1f, 0x5a, 0x16, 0x58, 0x5e, 0x16, 0xde, 0x7d, 0x1f, 0x86, 0x67, 0x06, 0xc4, 0x90, 0xc9,
	0xd6, 0xbc, 0x68, 0x5f, 0x8d, 0xda, 0x77, 0x55, 0xeb, 0x6c, 0x2d, 0xad, 0x33, 0xde, 0xe0, 0xe9,
	0x3f, 0xcd, 0xf4, 0xa4, 0x27, 0xb0, 0x5b, 0x32, 0x39, 0x3c, 0x82, 0x50, 0x37, 0x22, 0x38, 0x0b,
	0x2e, 0x0f, 0x8b, 0x50, 0x37, 0x69, 0x09, 0xc7, 0x77, 0x8e, 0x94, 0xa7, 0xa9, 0x2d, 0xe8, 0xfd,
	0x83, 0xd8, 0xaf, 0x21, 0x8c, 0x61, 0x8f, 0x7a, 0xa5, 0x5f, 0x45, 0x38, 0x7f, 0x7d, 0x05, 0x4c,
	0x20, 0xb2, 0x8a, 0x79, 0x34, 0xae, 0x11, 0x3b, 0x73, 0xf1, 0x93, 0xd3, 0x0b, 0x88, 0x0a, 0x62,
	0x6b, 0xde, 0x98, 0x50, 0xc0, 0x41, 0x4f, 0xcc, 0xaa, 0xa5, 0xef, 0x91, 0x4b, 0xbc, 0x66, 0x88,
	0xf3, 0x49, 0xf6, 0x41, 0xfb, 0x2e, 0x77, 0xb6, 0xbe, 0x27, 0x37, 0xe8, 0x9a, 0xf0, 0x09, 0xe0,
	0x57, 0x0a, 0xaf, 0xe4, 0xc6, 0x52, 0xf2, 0x8f, 0x79, 0x72, 0xbe, 0xc9, 0x2e, 0x3a, 0xb7, 0xf1,
	0x23, 0x0e, 0x59, 0xb5, 0x62, 0x9e, 0xf7, 0xe7, 0xfb, 0xdd, 0x7c, 0x06, 0x00, 0x00, 0xff, 0xff,
	0xc8, 0xe0, 0xa5, 0x06, 0x5b, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GokitWithGrpcServiceClient is the client API for GokitWithGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GokitWithGrpcServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*Response, error)
}

type gokitWithGrpcServiceClient struct {
	cc *grpc.ClientConn
}

func NewGokitWithGrpcServiceClient(cc *grpc.ClientConn) GokitWithGrpcServiceClient {
	return &gokitWithGrpcServiceClient{cc}
}

func (c *gokitWithGrpcServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/v1.gokit_with_grpc.grpc.GokitWithGrpcService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GokitWithGrpcServiceServer is the server API for GokitWithGrpcService service.
type GokitWithGrpcServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*Response, error)
}

// UnimplementedGokitWithGrpcServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGokitWithGrpcServiceServer struct {
}

func (*UnimplementedGokitWithGrpcServiceServer) CreateUser(ctx context.Context, req *CreateUserRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}

func RegisterGokitWithGrpcServiceServer(s *grpc.Server, srv GokitWithGrpcServiceServer) {
	s.RegisterService(&_GokitWithGrpcService_serviceDesc, srv)
}

func _GokitWithGrpcService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GokitWithGrpcServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.gokit_with_grpc.grpc.GokitWithGrpcService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GokitWithGrpcServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GokitWithGrpcService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.gokit_with_grpc.grpc.GokitWithGrpcService",
	HandlerType: (*GokitWithGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _GokitWithGrpcService_CreateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1.gokit_with_grpc.proto",
}
